export const list = [
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "1",
    type: "L",
    seatNo: "1",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "2",
    rowId: "1",
    columnId: "2",
    type: "R",
    seatNo: "2",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "3",
    rowId: "1",
    columnId: "4",
    type: "L",
    seatNo: "3",
    sectionId: "1",
    status: "2"
  },
  {
    index: "0",
    row: "1",
    column: "4",
    rowId: "1",
    columnId: "4",
    type: "R",
    seatNo: "4",
    sectionId: "1",
    status: "3"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "5",
    type: "N",
    seatNo: "5",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "6",
    type: "N",
    seatNo: "6",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "7",
    sectionId: "1",
    status: "0"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "8",
    type: "N",
    seatNo: "8",
    sectionId: "1",
    status: "0"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "9",
    sectionId: "1",
    status: "0"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "10",
    sectionId: "1",
    status: "0"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "11",
    sectionId: "1",
    status: "2"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "12",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "13",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "14",
    sectionId: "1",
    status: "2"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "15",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "16",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "17",
    sectionId: "1",
    status: "2"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "18",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "19",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "20",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "21",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "22",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "23",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "24",
    sectionId: "1",
    status: "1"
  },
  {
    index: "0",
    row: "1",
    column: "1",
    rowId: "1",
    columnId: "7",
    type: "N",
    seatNo: "25",
    sectionId: "1",
    status: "1"
  }
];
